works/MR/ASP.NET/MCMAIP/MCMAIP/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCMAIP.Controllers
{
    public class AboutUsController : Controller
    {
        //
        // GET: /AboutUs/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Company()
        {
            return View();
        }

        public ActionResult Team()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }

    }
}

works/MR/ASP.NET/MCMAIP/MCMAIP/Controllers/CooperateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCMAIP.Controllers
{
    public class CooperateController : Controller
    {
        //
        // GET: /Cooperate/

        public ActionResult Index()
        {
            return View();
        }

    }
}

works/MR/ASP.NET/MCMAIP/MCMAIP/Controllers/MentorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCMAIP.Controllers
{
    public class MentorController : Controller
    {
        //
        // GET: /Mentor/

        public ActionResult Index()
        {
            return View();
        }

    }
}

works/MR/ASP.NET/MCMAIP/MCMAIP/Controllers/NewsController.cs
using MCMAIP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using System.Web.Http;
//using System.Web.Http.Routing;

namespace MCMAIP.Controllers
{
    public class NewsController : Controller
    {
        //
        // GET: /News/
        MCMAIPEntities storeDB = new MCMAIPEntities();

        public ActionResult Index()
        {
            return View();
        }


        //[Route("a/video")]
        public ActionResult GetNews(int count)
        {
            var news = GetTopSellingNews(count);

            return Json(news, JsonRequestBehavior.AllowGet);

        }

        private List<News> GetTopSellingNews(int count)
        {
            // Group the order details by album and return
            // the albums with the highest count
            SampleData sd = new SampleData();
            //sd.InitializeDatabase(storeDB);
            sd.SeedData(storeDB);
            return storeDB.NewsList
                .OrderByDescending(a => a.Id)
                .Take(count)
                .ToList();
        }

        //
        // GET: /News/Detail/5

        public ActionResult Detail(int id)
        {
            SampleData sd = new SampleData();
            sd.SeedData(storeDB);
            var news = storeDB.NewsList.Single(a => a.Id == id);
            return View(news);
        }

        //
        // GET: /News/Search/5
        [Authorize(Roles = "Admin")]
        public ActionResult Search()
        {
            var newsList = GetTopSellingNews(10);

            return View(newsList);
        }

        //
        // POST: /News/Search/5

        [HttpPost]
        public ActionResult Search(String title)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                var newlist = storeDB.NewsList.Single(a => a.Title == title);
                return View(newlist);
            }
        }

        //
        // GET: /News/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /News/Search/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

works/MR/ASP.NET/MCMAIP/MCMAIP/Views/Shared/_FooterPartial.cshtml

<div id="footer">
	<div class="container">
		<div class="row-fluid">
			<div class="span2">
				<ul>
					<li class="first">动  态</li>
					<li>@Html.ActionLink("动态", "Index", "News")</li>
                    <li>@Html.ActionLink("搜索", "Search", "News")</li> 
				</ul>
			</div>
			<div class="span2">
				<ul>
					<li class="first">导师</li>
					<li>@Html.ActionLink("微软技术专家", "Index", "Mentor")</li>
				</ul>
			</div>
			<div class="span2">
				<ul>
					<li class="first">项目介绍</li>
					<li>@Html.ActionLink("南京微软孵化平台", "Index", "Recruitment")</li>
					<li>@Html.ActionLink("创业团队招募", "Content", "Recruitment")</li>
					<li>@Html.ActionLink("常见问题解答", "FAQ", "Recruitment")</li>
				</ul>
			</div>
			<div class="span2">
				<ul>
					<li class="first">关于我们</li>
					<li>@Html.ActionLink("平台简介", "Index", "AboutUs")</li>
					<li>@Html.ActionLink("运营公司", "Company", "AboutUs")</li>
					<li>@Html.ActionLink("管理团队", "Team", "AboutUs")</li>
					<li>@Html.ActionLink("联系我们", "Contactus", "AboutUs")</li>
				</ul>
			</div>
			<div class="span4">
				<h3 style="font-size:12px;margin-bottom: 5px;line-height:20px;text-align:center;
					margin-top: 25px;color:#888;">
					微软(中国)授权运营管理单位
				</h3>
				<span style="margin:0 auto;display:block;width:80px;"><img src="@Url.Content("~/Content/images/company_logo.png")" style="width:80px;"></span>
				<h3 style="font-size:12px;color:#888;margin-top:5px;text-align:center;line-height:16px;">
					南京小鹿创萌科技孵化器<br>运营管理公司
				</h3>
			</div>
		</div>
		<div class="footer" role="contentinfo" style="margin-top:0;">
			&copy; @DateTime.Now.Year crystal ZYH
		</div>
	</div>
</div>
<div class="fiexd-tool">
	<div class="erwm_ico"></div>
	<a class="backTop" href="#header"></a>
	<div class="erwm">
		<img src="@Url.Content("~/Content/images/wx.jpg")" alt=""/>
		<span class="text">关注微信公众号</span>
	</div>
</div>
<!--  <div style="text-align:center">
	   <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://"); document.write(unescape("%3Cspan id='cnzz_stat_icon_1256720367'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s11.cnzz.com/z_stat.php%3Fid%3D1256720367%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
   </div> -->


works/MR/ASP.NET/MCMAIP/MCMAIP/Views/Shared/_HeaderPartial.cshtml

<nav style="clear:both;">
    <div id="header" class="navbar">
        <div class="container ">
            <a class="logo" href="@Url.Content("~/Home")"> <img src="@Url.Content("~/Content/images/mva_logo.png")" alt="微软创投"> </a>
            <div id="logindisplay" style="float:right;">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <div class="nav-collapse pull-right">
                <ul id="menu-primary" class="nav">
                    <li>@Html.ActionLink("动态", "Index", "News")</li>
                    <li>@Html.ActionLink("导师", "Index", "Mentor")</li>
                    <li>
                        @Html.ActionLink("创业团队", "Index", "EnterPrise")
                        <!--  <ul>
                             <li><a href="enterPrise-1.html">一期团队</a></li>
                             <li><a href="enterPrise-2.html">二期团队</a></li>
                         </ul> -->
                    </li>
                    <li>@Html.ActionLink("合作伙伴", "Index", "Cooperate")</li>
                    <li>
                        @Html.ActionLink("申请入驻", "Index", "Recruitment")
                        <ul>
                            <li>@Html.ActionLink("南京微软孵化平台", "Index", "Recruitment")</li>
                            <li>@Html.ActionLink("创业团队招募", "Content", "Recruitment")</li>
                            <li>@Html.ActionLink("常见问题解答", "FAQ", "Recruitment")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("关于我们", "Index", "AboutUs")</li>

                </ul>
            </div>
        </div>
    </div>
</nav>


works/MR/ASP.NET/MCMAIP/MCMAIP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width,height=device-height,inital-scale=1.0,maximum-scale=1.0,user-scalable=yes">
    <title> 南京微软云暨移动应用孵化平台 - @ViewBag.Title </title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        @Html.Partial("_HeaderPartial")
    </header>

    <section id="main">
        <div id="container">
            <div class="container">
                @RenderSection("featured", required: false)
                @RenderBody()
            </div>
        </div>
    </section> 
    <footer>
        @Html.Partial("_FooterPartial")
    </footer>

        @*
               @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        *@


</body>
</html>